# Generated by Django 4.2.1 on 2023-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('association_id', models.CharField(max_length=100)),
                ('apartment_id', models.CharField(max_length=100)),
                ('eb_over_voltage', models.BooleanField(default=False)),
                ('eb_over_frequency', models.BooleanField(default=False)),
                ('eb_over_current', models.BooleanField(default=False)),
                ('eb_under_voltage', models.BooleanField(default=False)),
                ('eb_under_frequency', models.BooleanField(default=False)),
                ('eb_load_delay_time', models.IntegerField(default=0)),
                ('eb_tripping_delay_timer', models.IntegerField(default=0)),
                ('eb_trip_count', models.IntegerField(default=0)),
                ('dg_over_voltage', models.BooleanField(default=False)),
                ('dg_over_frequency', models.BooleanField(default=False)),
                ('dg_over_current', models.BooleanField(default=False)),
                ('dg_under_voltage', models.BooleanField(default=False)),
                ('dg_under_frequency', models.BooleanField(default=False)),
                ('dg_load_delay_time', models.IntegerField(default=0)),
                ('dg_tripping_delay_timer', models.IntegerField(default=0)),
                ('dg_trip_count', models.IntegerField(default=0)),
                ('dg_auto_reset_delay_timer', models.IntegerField(default=0)),
                ('dg_auto_retry_limit', models.IntegerField(default=0)),
                ('kwh_limit', models.FloatField(default=0.0)),
                ('dg_remote_delay', models.IntegerField(default=0)),
                ('phase', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
